apiVersion: apps/v1
kind: Deployment
metadata:
  name: tribute-page-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tribute-page
  template:
    metadata:
      labels:
        app: tribute-page
    spec:
      spec:
      containers:
        - name: tributeapp
          image: ebno1/tribute-page:latest
          ports:
            - containerPort: 4040