# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: tribute-page-deployment
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: tribute-page
#   template:
#     metadata:
#       labels:
#         app: tribute-page
#     spec:
#       spec:
#       containers:
#         - name: tributeapp
#           image: ebno1/tribute-page:latest
#           ports:
#             - containerPort: 4040


apiVersion: apps/v1
kind: Deployment
metadata:
  name: tribute-page-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tribute-page
  template:
    metadata:
      labels:
        app: tribute-page
    spec:
      containers:
      - name: tributeapp
        image: ebno1/tribute-page:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000