# apiVersion: v1
# kind: Service
# metadata:
#   name: tribute-page-service
# spec:
#   selector:
#     app: tribute-page
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 4040
#   type: LoadBalancer  

apiVersion: v1
kind: Service
metadata:
  name: tribute-page-service
spec:
  type: LoadBalancer
  selector:
    app: tribute-page
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP